def on_overlap_tile(sprite, location):
    game.game_over(True)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.chest_open,
    on_overlap_tile)

def on_on_overlap(sprite2, otherSprite):
    mySprite.set_position(24, 24)
    tiles.place_on_random_tile(mySprite2, sprites.castle.tile_dark_grass1)
    music.play(music.melody_playable(music.power_up),
        music.PlaybackMode.UNTIL_DONE)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

mySprite2: Sprite = None
mySprite: Sprite = None
mySprite = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . c c . . . . . . 
            . . . . . c a a a a . . . . . . 
            . . . . . a a f f b a . . . . . 
            . . . . c a b f f c b . . . . . 
            . . . . c b b b a f c b . . . . 
            . . . . c b a c a b b b . . . . 
            . . . . . b b f f a a c . . . . 
            . . . . . . a a b b c . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.player)
controller.move_sprite(mySprite)
tiles.set_current_tilemap(tilemap("""
    level2
"""))
scene.camera_follow_sprite(mySprite)
mySprite.set_position(24, 24)
mySprite2 = sprites.create(img("""
        ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.enemy)
mySprite2.follow(mySprite, 50)
tiles.place_on_random_tile(mySprite2, sprites.castle.tile_dark_grass1)
info.start_countdown(20)

def on_forever():
    global mySprite2
    mySprite2 = sprites.create(img("""
            ........................
                    .....ffff...............
                    ...fff22fff.............
                    ..fff2222fff............
                    .fffeeeeeefff...........
                    .ffe222222eef...........
                    .fe2ffffff2ef...........
                    .ffffeeeeffff...........
                    ffefbf44fbfeff..........
                    fee41fddf14eef..........
                    .ffffdddddeef...........
                    fddddf444eef............
                    fbbbbf2222f4e...........
                    fbbbbf2222fd4...........
                    .fccf45544f44...........
                    ..ffffffff..............
                    ....ff..ff..............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        SpriteKind.enemy)
    mySprite2.follow(mySprite, 50)
    tiles.place_on_random_tile(mySprite2, sprites.castle.tile_dark_grass1)
    pause(2000)
forever(on_forever)
